export const CHANGE_MAP_CITY = "CHANGE_MAP_CITY";

export const CHANGE_WEATHER_CITY = "CHANGE_WEATHER_CITY";

export const DELETE_CITY = "DELETE_CITY";

export const TOGGLE_CITY = "TOGGLE_CITY";

export const UPDATE_DIRECTION = "UPDATE_DIRECTION";

export const SET_HEADER = "SET_HEADER";

export const SET_NOW_WEATHER = "SET_NOW_WEATHER";

export const SET_FUTURE_WEATHER = "SET_FUTURE_WEATHER";

export const SET_ATTRACTIONS = "SET_ATTRACTIONS";

export const SET_CATEGORIES = "SET_CATEGORIES";

export const SET_USER = "SET_USER";

export const PUSH_TRIP_ATTRACTION = "PUSH_TRIP_ATTRACTION";

export const SET_MENU = "SET_MENU";

export const CLEAN_TRIPATTRACTION = "CLEAN_TRIPATTRACTION";

export const DELETE_ATTRACION = "DELETE_ATTRACION";
